### PR TITLE
Relicense under BSD

### LINKED ISSUE #27: GPL License
As far as I understand it, adding this module to my Django project makes the entire application GPL. This makes usage in a professional setting difficult.

I fully agree with the principle of avoiding lock-in and of having something based on your work being shared with the community, but it's a little excessive to force this on the entire application for what is in all honesty a relatively minor component of the stack.

I would gladly contribute to djangocms-page-sitemap if I make any changes to it... I'm a little less comfortable in sharing all my work and forcing my customers to do the same.

I would suggest changing the license to LGPLv3 which doesn't have the "viral" attribute of the GPL but still keeps all the other freedoms intact.

GPL is usually for entire applications, LGPL for libraries or modules.

Thank you.

### PR DESCRIPTION
**Pull request by yakky**
We have decided to relicense this under BSD for compatibility with the Django ecosystem

I ask past contributors to approve this PR by January 31st

Fix #27

### CODE REVIEW

**Comment by yakky** [comment]
@carderm @satyrius @jeroenpeters1986 could you please approve this PR to accept relicensing your contribution?

**Comment by yakky** [comment]
Thanks @satyrius :bowing_man:

**Comment by yakky** [comment]
@carderm thanks! :bowing_man:

**Comment by jeroenpeters1986** [comment]
So sorry I missed this, will do!

**Comment by jeroenpeters1986** [comment]
@yakky done!

**Comment by yakky** [comment]
@jeroenpeters1986 :bowing_man: Thanks a lot

**Comment by yakky** [comment]
Merging this :clap:

**Pull request merged**
